services:
    user.php:
        build: docker/php
        environment:
            XDEBUG_MODE: develop,debug,coverage
            XDEBUG_CONFIG: client_host=192.168.0.114
            PHP_IDE_CONFIG: serverName=api.user.local
        working_dir: /var/www/user
        volumes:
            - .:/var/www/user:rw
        links:
            - user.db
    user.nginx:
        image: nginx:alpine-slim
        volumes:
            - .:/var/www/user:rw
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - user.php

    ###> doctrine/doctrine-bundle ###
    user.db:
        image: postgres:${POSTGRES_VERSION:-16}-alpine
        shm_size: 128mb
        environment:
            POSTGRES_DB: ${DB_NAME:-marketplace}
            # You should definitely change the password in production
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-SuperPass123}
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
        healthcheck:
            test: [ "CMD", "pg_isready", "-d", "${DB_NAME:-app}", "-U", "${POSTGRES_USER:-app}" ]
            timeout: 5s
            retries: 5
            start_period: 60s
        volumes:
            - database_user_data:/var/lib/postgresql/data:rw
            # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
            # - ./docker/db/data:/var/lib/postgresql/data:rw
    ###< doctrine/doctrine-bundle ###

volumes:
    ###> doctrine/doctrine-bundle ###
    database_user_data:
    ###< doctrine/doctrine-bundle ###